Repository Ant-Shell/dnd-stretch-tech, pull requests merged in 2022-09, with the labels that each got.

#1 Configuration/setup
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .gitignore
  README.md
  docs/.README.md
  docs/pull_request_template.md
  package.json
  public/index.html
  src/components/App/App.css
  src/components/App/App.js
  src/index.css
  src/index.js
Labels: enhancement

#3 Configuration/setup typescript
  README.md
  docs/.README.md
  docs/pull_request_template.md
  package.json
  public/index.html
  src/components/App/App.tsx
  src/index.tsx
  src/react-app-env.d.ts
  tsconfig.json
Labels: enhancement

#4 Configuration/setup typescript
  package.json
  src/tsconfig.json
  tsconfig.json
Labels: enhancement

#16 Configuration/setup typescript2
  .gitignore
  package.json
  src/Components/App.tsx
  src/Styles/App.css
  src/components/App/App.css
  src/components/App/App.tsx
  src/index.css
  src/index.tsx
  src/tsconfig.json
  tsconfig.json
Labels: enhancement

#19 Feature/character creation form
  src/Components/App.tsx
  src/Components/CharacterCreator.tsx
  src/Components/MainSection.tsx
  src/Components/MonsterDetails.tsx
  src/Components/MonsterSection.tsx
  src/Components/MonstersList.tsx
  src/Components/Party.tsx
  src/Styles/Party.css
  src/types.tsx
Labels: mvp

#21 Add delete button functionality for party members
  src/Components/MainSection.tsx
  src/Components/Party.tsx
Labels: mvp

#22 Add Blurb Rendering and finish Monster Page functionality
  src/ClassBlurbs.tsx
  src/Components/App.tsx
  src/Components/BlurbBox.tsx
  src/Components/CharacterCreator.tsx
  src/Components/MainSection.tsx
  src/Components/MonsterDetails.tsx
  src/Components/MonsterSection.tsx
  src/Styles/BlurbBox.css
  src/Styles/CharacterCreator.css
  src/Styles/MonsterDetails.css
Labels: mvp

#24 Feature/refactor form
  src/Components/CharacterCreator.tsx
  src/Components/Party.tsx
Labels: bug fix

#43 Feature/search monsters name
  src/Components/MonsterDetails.tsx
  src/Components/MonsterSection.tsx
  src/Components/Nav.tsx
  src/Styles/MonsterDetails.css
Labels: extension

#44 Update variable types FormInputs PartyStructure CharacterStructure
  src/types.tsx
Labels: bug fix

#51 No party duplicates
  src/Components/App.tsx
  src/Components/CharacterCreator.tsx
  src/Components/CharacterSection.tsx
  src/Components/Party.tsx
Labels: extension

#56 Refactor/error handing and adjustments
  public/index.html
  src/Components/App.tsx
  src/Components/CharacterCreator.tsx
  src/Components/MonsterDetails.tsx
  src/Components/MonsterSection.tsx
  src/Components/MonstersList.tsx
  src/Styles/CharacterCreator.css
  src/Styles/MonsterDetails.css
  src/Styles/Party.css
Labels: enhancement

#55 Add background image
  src/Components/Nav.tsx
  src/Styles/App.css
  src/Styles/BlurbBox.css
  src/Styles/CharacterCreator.css
  src/Styles/MonsterDetails.css
  src/Styles/MonstersList.css
  src/Styles/Nav.css
  src/Styles/Party.css
Labels: extension

#57 Add custom logo and favicon
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  src/Components/MonsterDetails.tsx
  src/Components/Nav.tsx
  src/Styles/CharacterCreator.css
  src/Styles/MonsterDetails.css
  src/Styles/Nav.css
  src/Styles/Party.css
Labels: enhancement, extension

#67 Styling/media queries and accessibility
  cypress/e2e/1-homepage-view/homepage.cy.js
  cypress/e2e/2-monsterspage/monsterspage.cy.js
  public/index.html
  src/Components/BlurbBox.tsx
  src/Components/CharacterCreator.tsx
  src/Components/Error.tsx
  src/Components/MonsterDetails.tsx
  src/Components/MonstersList.tsx
  src/Components/Nav.tsx
  src/Styles/CharacterCreator.css
  src/Styles/MonsterDetails.css
  src/Styles/MonstersList.css
  src/Styles/Nav.css
  src/Styles/Party.css
Labels: enhancement, extension
